# Generated by Django 3.1.3 on 2020-11-18 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogoCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img', verbose_name='Изображение')),
                ('name', models.CharField(max_length=5, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='NavList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='Заголовок')),
                ('identifier', models.CharField(max_length=15, verbose_name='id')),
            ],
        ),
        migrations.CreateModel(
            name='HeaderBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(decimal_places=0, max_digits=11, verbose_name='Номер телефrона(без +)')),
                ('logo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='constructor.logocompany', verbose_name='Логотип компании')),
                ('navs', models.ManyToManyField(to='constructor.NavList', verbose_name='Навигация')),
            ],
        ),
    ]
