# Generated by Django 3.1.3 on 2020-11-21 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('constructor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название блока на английском')),
                ('title', models.CharField(max_length=20, verbose_name='Название блока на русском')),
                ('description', models.TextField(blank=True, max_length=100, verbose_name='Описание блока')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_uppdate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Информация об блоке',
                'verbose_name_plural': 'Информация об блоках',
            },
        ),
        migrations.CreateModel(
            name='HaveQuestionsBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=25, verbose_name='Заголовок')),
                ('content', models.CharField(max_length=300, verbose_name='Сообщение')),
                ('link_to_teleport', models.CharField(max_length=50, verbose_name='Название блока(англ) на который будет ссылаться')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor.blockinfo', verbose_name='Информация об блоке')),
            ],
            options={
                'verbose_name': "Блок - 'Остались вопросы?'",
                'verbose_name_plural': "Блоки - 'Остались вопросы?'",
            },
        ),
        migrations.CreateModel(
            name='KAMAZ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название камаза')),
                ('img', models.ImageField(upload_to='kamaz', verbose_name='Фото камаза')),
                ('description', models.TextField(max_length=100, verbose_name='Описание камаза')),
            ],
            options={
                'verbose_name': 'Камаз',
                'verbose_name_plural': 'Камазы',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Почта подтверждена')),
                ('token', models.CharField(max_length=30, verbose_name='Токен для подтверждени почты')),
                ('is_online', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Вопрос клиента',
                'verbose_name_plural': 'Вопросы клиентов',
            },
        ),
        migrations.CreateModel(
            name='RegistrationBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('have_questions', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.havequestionsblock', verbose_name='Остались вопросы?')),
            ],
            options={
                'verbose_name': 'Зарегистрировать блок',
                'verbose_name_plural': 'Регистрация блоков',
            },
        ),
        migrations.CreateModel(
            name='SendQuestionBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=25, verbose_name='Заголовок')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('number', models.DecimalField(decimal_places=0, max_digits=11, verbose_name='Номер телефrона(без +)')),
                ('working', models.CharField(max_length=30, verbose_name='График работы')),
                ('insta', models.CharField(max_length=100, verbose_name='Ссылка на инсту')),
                ('telega', models.CharField(max_length=100, verbose_name='Ссылка на телегу')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor.blockinfo', verbose_name='Информация об блоке')),
                ('kamaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor.kamaz', verbose_name='Пример камаза')),
            ],
            options={
                'verbose_name': "Блок - 'Отправить вопросы'",
                'verbose_name_plural': "Блоки - 'Отправить вопросы'",
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название сборки блоков')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Описание сборки')),
                ('content', models.ManyToManyField(to='constructor.RegistrationBlock', verbose_name='Блоки')),
            ],
            options={
                'verbose_name': 'Контент',
                'verbose_name_plural': 'Контент сайта',
            },
        ),
        migrations.AlterModelOptions(
            name='headerblock',
            options={'verbose_name': 'Блок - шапка сайта', 'verbose_name_plural': 'Блоки - шапка сайта'},
        ),
        migrations.RemoveField(
            model_name='headerblock',
            name='navs',
        ),
        migrations.AddField(
            model_name='headerblock',
            name='link_to_teleport',
            field=models.CharField(default=1, max_length=50, verbose_name='Название блока(англ) на который будет ссылаться'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='headerblock',
            name='logo',
            field=models.CharField(max_length=8, verbose_name='Лого'),
        ),
        migrations.DeleteModel(
            name='LogoCompany',
        ),
        migrations.DeleteModel(
            name='NavList',
        ),
        migrations.AddField(
            model_name='registrationblock',
            name='header',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.headerblock', verbose_name='Шапка'),
        ),
        migrations.AddField(
            model_name='registrationblock',
            name='send_question',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.sendquestionblock', verbose_name='Отправить вопрос'),
        ),
        migrations.AddField(
            model_name='havequestionsblock',
            name='kamaz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor.kamaz', verbose_name='Пример камаза'),
        ),
        migrations.AddField(
            model_name='headerblock',
            name='info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='constructor.blockinfo', verbose_name='Информация об блоке'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='headerblock',
            name='kamaz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='constructor.kamaz', verbose_name='Пример камаза'),
            preserve_default=False,
        ),
    ]
