# Generated by Django 3.1 on 2020-11-21 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0002_auto_20201121_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationblock',
            name='have_questions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.havequestionsblock', verbose_name='Остались вопросы?'),
        ),
        migrations.AlterField(
            model_name='registrationblock',
            name='header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.headerblock', verbose_name='Шапка'),
        ),
        migrations.AlterField(
            model_name='registrationblock',
            name='send_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.sendquestionblock', verbose_name='Отправить вопрос'),
        ),
    ]
