# Generated by Django 3.1 on 2020-11-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0003_auto_20201121_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='sorting',
            field=models.CharField(choices=[('default', 'Без изменений'), ('count-max', 'По возрастанию кол-ва блоков'), ('count-min', 'По убыванию кол-ва блоков'), ('random', 'Случайная сортировка')], default='default', max_length=20, verbose_name='Сортировка'),
        ),
    ]
