# Generated by Django 3.1 on 2020-11-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0004_sitecontent_sorting'),
    ]

    operations = [
        migrations.AddField(
            model_name='havequestionsblock',
            name='type_block',
            field=models.CharField(default='HaveQuestionsBlock', max_length=50, verbose_name='Тип блока'),
        ),
        migrations.AddField(
            model_name='headerblock',
            name='type_block',
            field=models.CharField(default='HeaderBlock', max_length=50, verbose_name='Тип блока'),
        ),
        migrations.AddField(
            model_name='sendquestionblock',
            name='type_block',
            field=models.CharField(default='SendQuestionBlock', max_length=50, verbose_name='Тип блока'),
        ),
    ]
